### ISSUE TITLE
propaganistas/laravel-cache-keywords IS DELETED???

### ISSUE THREAD

**Issue by unitedworx** [Propaganistas/Laravel-Disposable-Email#14]
sorry for writing this here

propaganistas/laravel-cache-keywords IS DELETED???

I was using this in many projects nd now ALL are broken!

can you please bring this back? or at least send me the zip to add on my account?

**Comment by Propaganistas** [comment]
The package has been marked as abandoned on Packagist for over a year. From that point on all composer installs and updates showed clear warnings. There was ample time to move on and update any applications.

I see you’ve been able to create a repo yourself, so I’m closing this.

**Comment by unitedworx** [comment]
I have 50 projects using this package

It’s not feasible to update all old projects that are stuck to Laravel 5.1

Surely new projects based on ew Laravel version are Handled differently.

By deleting  this repo you have broken all old repos that we’re using this as a depandancu

I haven't Been able to use my cloned repo via composer

Kindest Regards,

Paris Paraskeva
Managing Director
M.E. & E. United Worx Ltd
33, Apostolou Pavlou Avenue, Office 103, 8046 Paphos, Cyprus
Tel.: +357 26220707 , Fax.: +357 26221002
Mob.: +357 99575501
paris@unitedworx.com , www.unitedworx.com


On 17 Apr 2020, at 2:37 PM, Propaganistas <notifications@github.com> wrote:

﻿

Closed #14<https://github.com/Propaganistas/Laravel-Disposable-Email/issues/14>.

**Comment by Propaganistas** [comment]
Add your Github repo url to composer.json as described here: https://stackoverflow.com/a/41471934

**Comment by unitedworx** [comment]
I moved your code internally In my projects. Unfortunately I will also have to patch every single project that I touch! Beauty of composer is also it’s curse when a reporter like yours is deleted ! That why I told you you shouldn’t have removed this! I know it’s deprecated ! But old projects depend on it.


Kindest Regards,

Paris Paraskeva
Managing Director
M.E. & E. United Worx Ltd
33, Apostolou Pavlou Avenue, Office 103, 8046 Paphos, Cyprus
Tel.: +357 26220707 , Fax.: +357 26221002
Mob.: +357 99575501
paris@unitedworx.com , www.unitedworx.com


On 17 Apr 2020, at 3:04 PM, Propaganistas <notifications@github.com> wrote:

﻿

Add your Github repo url to composer.json as described here: https://stackoverflow.com/a/41471934
