### ISSUE TITLE
Feature request - use curl instead of file_get_contents

### ISSUE THREAD

**Issue by atanas18** [Propaganistas/Laravel-Disposable-Email#20]
https://github.com/Propaganistas/Laravel-Disposable-Email/blob/1f7d721c37845d390dffb38c27b1a361b40ac13e/src/Console/UpdateDisposableDomainsCommand.php#L107

Probably add a way to download the file with curl, as in many cases php is set with "allow_url_fopen = Off" on production environments for security reasons, so file_get_contents doesn't work with URLs.

Thanks.

**Comment by Propaganistas** [comment]
~~I'm open for a PR that exposes a configuration option referencing the class responsible for handling the file download.~~

Available in `2.1.3`.

**Comment by Propaganistas** [comment]
Updated my comment above.
