### ISSUE TITLE
preg_match fails

### ISSUE THREAD

**Issue by backendrulz** [Propaganistas/Laravel-Disposable-Email#3]
Hello!
https://github.com/Propaganistas/Laravel-Disposable-Email/blob/b93d8659f436f379a7bbaf09bbb6de3628fd7330/src/DisposableDomains.php#L113

Matches:  user@yahoo.com.ar as 
```
array:1 [
  0 => "com.ar"
]
```

**Comment by Propaganistas** [comment]
Could you please describe any issue you're facing?

`com.ar` is listed as a disposable domain, so any subdomain such as `yahoo.com.ar` is regarded as disposable as well.

**Comment by Propaganistas** [comment]
Thanks. I'll implement this bug fix in the next release. Will be available in a few moments.
