### ISSUE TITLE
External storage support

### ISSUE THREAD

**Issue by bloomlive** [Propaganistas/Laravel-Disposable-Email#31]
When using AWS Lambda, you cannot write to disc unless you provide additional storage and S3 is the default way. Would it be a great deal to support?

**Comment by Propaganistas** [comment]
You can give it a go and open a PR if you like. I'm thinking along the lines of implementing support for choosing the disk which will allow you to choose S3 or any other filesystem defined in `config/filesystems.php`.

For example refactor the config:
```php
'storage' => storage_path('framework/disposable_domains.json'),
```
to
```php
'storage' => [
    'disk' => 'local',
    'path' => ...,
],
```
and then consume those configuration values in the package's logic.

**Comment by Propaganistas** [comment]
I gave it a shot anyway.
Could you please try branch "feature-#31" and report back if this works out for you?

Laravel 9 is minimally required because of inconsistencies between Flysystem v1 (Laravel < 9) and v3 (Laravel 9).

**Comment by jdavidbakr** [comment]
Did this get impemented?  I don't see the PR for it referenced here.  I'd like to use this package but have a distributed container-based architecture and can't use local storage.

**Comment by Propaganistas** [comment]
No. Feel free to open a new PR.
