### ISSUE TITLE
Feature request: console command for checking existing users and being able to perform some logic

### ISSUE THREAD

**Issue by sts-ryan-holton** [Propaganistas/Laravel-Disposable-Email#34]
Hi :wave:

I've recently installed this package into my Laravel 9 and PHP 8 web application, I've published the config, set up the weekly cron, and everything is working as intended I believe.

My feature request, is really to be able to somehow provide some kind of command of some description that I can run, and update some column on my `User` model, for example, some systems may want to allow anyone to sign up, or may indeed (like myself) already have a platform with quite a few users and cannot delete them, but instead, want to create some validation column in the `User` model for reporting and email marketing purposes.

There's not really any point in sending marketing emails to temp email addresses if they were once valid for 10 minutes, some months ago in the present day.

Is this something that could be added?

**Comment by Propaganistas** [comment]
That seems like a highly specific & opinionated command. You've got all the tools you need to create such a command:

- Create a new Laravel Command class
- loop each user
- validate the existing email using this package's validator
- update column when applicable

Good luck!
