### ISSUE TITLE
Automatically excluding disposable_domains from version control

### ISSUE THREAD

**Issue by sts-ryan-holton** [Propaganistas/Laravel-Disposable-Email#35]
When running the `disposable:update` command, in generates `storage/framework/disposable_domains.json`, except this `framework` folder in general contains folders such as cache that are outside of git, I don't think it's necessary to include it in version control by default since running the `update` command replaces it anyway?

**Comment by Propaganistas** [comment]
The general folders are Laravel-managed, so best to stay out of there. But of course you're free to add the file to your project's `storage/framework/.gitignore`
