### ISSUE TITLE
Update command runs on each test

### ISSUE THREAD

**Issue by NanoNulla** [Propaganistas/Laravel-Disposable-Email#36]
> PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8388616 bytes) in /home/runner/work/uwcore/uwcore/vendor/propaganistas/laravel-disposable-email/src/DisposableDomains.php on line 124

I have the above issue when I run the test on GitHub action. It calls the update command on each test.
@Propaganistas one possible way to solve this is to create a condition about the last modification time of the `.json` file in command so the draft condition would be. 

```php
public function handle(Config $config, DisposableDomains $disposable){

  // check the last modification time > 10 minute 

  // if so, run the command

  // else return 0 the command.

   ...

}
```

**Comment by Propaganistas** [comment]
Or:
- don't call the command during testing. It's already tested in the package.
- wrap the code that's calling the command in a conditional

**Comment by NanoNulla** [comment]
Thanks @Propaganistas
