### ISSUE TITLE
Is there support for validating array of emails?

### ISSUE THREAD

**Issue by djurovicigoor** [Propaganistas/Laravel-Disposable-Email#38]
Is there support for validating an array of emails? Or maybe some function to call statically and validate emails in the controller or somewhere else?

**Comment by Propaganistas** [comment]
You can call the package's `isDisposable()` / `isNotDisposable()` methods freely. They accept a single string, so just loop over your array if you need it like that.

```php
app(DisposableDomains::class)->isDisposable($email);
```

If needed in Laravel's validation, you can use built-in features to achieve that: [nested array inputs](https://laravel.com/docs/10.x/validation#validating-nested-array-input) or use a [closure](https://laravel.com/docs/10.x/validation#using-closures)

**Comment by djurovicigoor** [comment]
Thank you!
