### ISSUE TITLE
Cache using DynamoDB or Database

### ISSUE THREAD

**Issue by felipehertzer** [Propaganistas/Laravel-Disposable-Email#43]
Hi, 

When I'm using the cache driver Dynamodb I receive the error "Item size has exceeded the maximum allowed size", The reason is that Dynamodb has a limit of 400KB.

Also, when using Database as a driver, I receive the error "NOTICE  unserialize(): Error at offset 10 of 65535 bytes in vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php on line 403.".

Any Ideia how to fix it or maybe split the domains to be able to use one of that drivers?

Thank you.

**Comment by Propaganistas** [comment]
Tough one. One could consider splitting the cached value into multiple smaller cached chunks, but I'm unsure what the impact would be in terms of speed when compared to using the plain old `file` driver...

**Comment by Propaganistas** [comment]
Btw, I cannot seem to reproduce the database unserialization issue.
