### ISSUE TITLE
SimpleLogin domains marked in your disposable emails list

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [Propaganistas/Laravel-Disposable-Email#44]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of disposable emails. To be more precise, dralias.com, 8alias.com, 8shield.net, slmail.me, are included.

Could we trouble you to please clarify why this is the case? Would it be possible to correct this? 

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by Propaganistas** [comment]
As stated in the readme the domains list is entirely fed by https://github.com/disposable/disposable
You'll have to redirect your inquiry to that repository.

The file in this repository is synced weekly, so if it disappears over there, it'll also be gone here.
