### ISSUE TITLE
duck.com incorrectly listed as a disposable email service

### ISSUE THREAD

**Issue by astroblaster** [Propaganistas/Laravel-Disposable-Email#45]
Hello,

I'm writing as a postmaster for duck.com, DuckDuckGo's email forwarding service.

It seems we've landed on your list as a disposable email. We don't intend for our service to be used as a disposable email. We take any reports of abuse seriously. Would you consider removing this entry?

Thank you,

Brian Kowalewicz

**Comment by Propaganistas** [comment]
As stated in the readme the domains list is entirely fed by https://github.com/disposable/disposable
You'll have to redirect your inquiry to that repository.

The file in this repository is synced weekly, so if it disappears over there, it'll also be gone here.
