### ISSUE TITLE
New report of disposable 

### ISSUE THREAD

**Issue by ghost** [Propaganistas/Laravel-Disposable-Email#48]
Provider is https://skiff.com/quick-alias and it's actually subdomains, each user can generate their own subdomain. I tested it, very easy.

The page title of https://skiff.com/quick-alias is "Quick alias burner email address". In the HTML I see

```
<meta name="description" content="Secure and quick-to-create burner email addresses with Skiff!
```

There is a browser plugin https://github.com/irazasyed/email-masker to create one email per website, skiff.com's twitter account promoted it, the github repository is tagged as 'burner-email'

You should add:

- `maskmy.id` because it is there main domain
- `anything.maskmy.id` because it allows you to create disposable addresses with random subdomains

![IMG_1500](https://github.com/7c/fakefilter/assets/153666218/b6886eac-1833-4d68-9899-b2c818de6744)
![IMG_1501](https://github.com/7c/fakefilter/assets/153666218/18fc93da-1a1d-490b-97e4-5fb12b82903e)

**Comment by Propaganistas** [comment]
As stated in the readme the domains list is entirely fed by https://github.com/disposable/disposable
You'll have to redirect your inquiry to that repository.

The file in this repository is synced weekly, so if it disappears over there, it'll also be gone here.
