### ISSUE TITLE
The domain source contains a valid domain - zoho.com

### ISSUE THREAD

**Issue by stueynet** [Propaganistas/Laravel-Disposable-Email#49]
Zoho.com is on the list however Zoho is a valid organization and not a disposable email tool afaik. 

https://cdn.jsdelivr.net/gh/disposable/disposable-email-domains@master/domains.json

**Comment by Propaganistas** [comment]
As stated in the readme the domains list is entirely fed by https://github.com/disposable/disposable
You'll have to redirect your inquiry to that repository.

The file in this repository is synced weekly, so if it disappears over there, it'll also be gone here.

**Comment by stueynet** [comment]
> As stated in the readme the domains list is entirely fed by https://github.com/disposable/disposable
> 
> You'll have to redirect your inquiry to that repository.
> 
> 
> 
> The file in this repository is synced weekly, so if it disappears over there, it'll also be gone here.

Oh boy sorry! Totally missed that. Will post an issue over there. Thanks!
