### ISSUE TITLE
Subdomains bypass validation

### ISSUE THREAD

**Issue by stri8ed** [Propaganistas/Laravel-Disposable-Email#53]
Its possible to bypass the validation by using subdomains of the disposable domains. e.g.

```
min82595@jzxz.crankymonkey.info
kimberley51461@8a7b.cashbenties.com
```
The root domains are blocked, but the validation logic [does not detect these](https://github.com/Propaganistas/Laravel-Disposable-Email/blob/c5edfb26d5622cdfb4b040689a85c1f584b49077/src/DisposableDomains.php#L164), since it checks the entire domain as single string.

I am seeing cases of people abusing this in the wild. I assume the disposable providers offer dynamic subdomains as an option.

**Comment by Propaganistas** [comment]
Validation is performed similarly to what [disposable/disposable](https://github.com/disposable/disposable) offers for JS:
See https://github.com/disposable/disposable/blob/7c19066bc3765767d5427f6da8334a3e70687f82/disposable.js#L11-L12

But I'm open for a PR with tests providing a configuration option for that.
