### ISSUE TITLE
[Feature Request] Update list from behind a proxy

### ISSUE THREAD

**Issue by JavanCook** [Propaganistas/Laravel-Disposable-Email#6]
Currently when behind a proxy running the update artisan command gets the unable to reach source error message.

If the artisan command is passed an option would it be possible to grab a field, such as `INTERNAL_PROXY` from the `.env` file or something from the config, to be able to grab the updated list when behind a proxy?

https://stackoverflow.com/questions/1336262/file-get-contents-behind-a-proxy

**Comment by Propaganistas** [comment]
I'm open for a PR using Guzzle and a dedicated class handling the HTTP call that can be overriden in config to accommodate to situations like when behind a proxy.

**Comment by Propaganistas** [comment]
This feature is now available.
